# Generated by Django 6.1 on 2026-08-31 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAmbience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A quiet afternoon', max_length=150)),
                ('artist', models.CharField(default='The Reading Room', max_length=150)),
                ('audio_file', models.FileField(blank=True, help_text='Upload music you have permission to use. Maximum 20 MB.', upload_to='library_music/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])])),
                ('audio_url', models.URLField(blank=True, help_text='Or use a direct HTTPS audio URL, not a streaming-service page.')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Library soundtrack',
                'verbose_name_plural': 'Library soundtrack',
            },
        ),
    ]
