# Generated by Django 6.1 on 2026-08-31 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_libraryambience'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, help_text='HTTPS cover image URL. Filled by Google Books, or supply your own licensed cover.', max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
